# 项目相关配置
sanwei:
  # 名称
  name: SanWei
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/sanwei/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.sanwei: debug
    org.springframework: warn
    org.mybatis: debug

swagger:
  enabled: true
  pathMapping: /dev-api

spring:
  messages:
    basename: i18n/messages
  profiles:
    active: druid

# MyBatis配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 搜索指定包别名
  typeAliasesPackage: com.sanwei.**.domain
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml